In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('ClosedStack_data_Virtual.csv', low_memory= False, encoding='latin-1')


In [ ]:
# "Job ID","Job Status","Job Klass","Job Hardware ID","Job Operation","Job Created","Job Updated",
#"Job Duration in Seconds","Job Ticket ID","Hardware ID","Hardware Name","Hardware Image ID",
#"Hardware Solution ID","Hardware Site ID","Image ID","Image Name","Site ID","Site Name","Ticket Site Name",
#"First Site Name","Solution ID","Solution Name","Ticket ID","Ticket Site","Hardware Compute Config ID",
#"Compute Config ID","Compute Config Name","Compute Config CPU","Compute Config Memory","Compute Config Disk",
#"Compute Config SKU"

In [ ]:
#ticket site, site name, solution name, hardware name/id, job created (in years/months)
#df_year_2021 = df_main.loc[(df_main['Job Created'] <= "2022-01-01 00:00:00.000000") & (df_main['Job Created'] >= "2021-01-01 00:00:00.000000")]

In [3]:
df_new = df[[ 'Job ID','Hardware ID', 'Hardware Name', 'Solution ID', 'Ticket Site','Site Name', 'Job Created']]

In [22]:

yearly_data = {}

start_year = 2018
end_year = 2022

for year in range(start_year, end_year + 1):
    monthly_data = {}
    
    for month in range(1, 13):
        monthstart = f"{year}-{month:02d}-01"
        monthend = f"{year}-{month + 1:02d}-01" if month < 12 else f"{year + 1}-01-01"
        
        filtered_df = df_new.loc[(df_new['Job Created'] >= monthstart) & (df_new['Job Created'] < monthend)]
        monthly_data[f'df_new_{year}_{month:02d}'] = filtered_df
    
    
    yearly_data[year] = monthly_data

years = [2018, 2019, 2020, 2021, 2022]
months = ['01', '02', '03', '04', '05', '06', '07', '08', '09', '10', '11', '12']


for year in years:
    for month in months:
        variable_name = f'df{year}{month}'
        length = len(yearly_data[year][f'df_new_{year}_{month}'])
        exec(f"{variable_name} = {length}")




In [16]:
print (df202201)

839


In [15]:
print (df202101)

1801


In [ ]:

numberofjobspermonth2018 = [df201801, df201802, df201803, df201804, df201805, df201806, df201807, df201808, df201809, df201810, df201811, df201812]
yearly_index = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

yearly_df = pd.DataFrame({'Number of Jobs' : numberofjobspermonth2018}, index=yearly_index)

ax = yearly_df.plot.bar(rot=0, title = 'Amount of servers requested per month, 2018')

In [ ]:
numberofjobspermonth2019 = [df201901, df201902, df201903, df201904, df201905, df201906, df201907, df201908, df201909, df201910, df201911, df201912]
yearly_index = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

yearly_df = pd.DataFrame({'Number of Jobs' : numberofjobspermonth2019}, index=yearly_index)

ax = yearly_df.plot.bar(rot=0, title = 'Amount of servers requested per month, 2019')

In [ ]:
numberofjobspermonth2020 = [df202001, df202002, df202003, df202004, df202005, df202006, df202007, df202008, df202009, df202010, df202011, df202012]
yearly_index = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

yearly_df = pd.DataFrame({'Number of Jobs' : numberofjobspermonth2020}, index=yearly_index)

ax = yearly_df.plot.bar(rot=0, title = 'Amount of servers requested per month, 2020')

In [ ]:
numberofjobspermonth2021 = [df202101, df202102, df202103, df202104, df202105, df202106, df202107, df202108, df202109, df202110, df202111, df202112]
yearly_index = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

yearly_df = pd.DataFrame({'Number of Jobs' : numberofjobspermonth2021}, index=yearly_index)

ax = yearly_df.plot.bar(rot=0, title = 'Amount of servers requested per month, 2021')

In [ ]:
numberofjobspermonth2022 = [df202201, df202202, df202203, df202204, df202205, df202206, df202207, df202208, df202209, df202210, df202211, df202212]
yearly_index = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']

yearly_df = pd.DataFrame({'Number of Jobs' : numberofjobspermonth2022}, index=yearly_index)

ax = yearly_df.plot.bar(rot=0, title = 'Amount of servers requested per month, 2022')

In [25]:
df202202

1196

In [26]:
# df_new = df[[ 'Job ID','Hardware ID', 'Hardware Name', 'Solution Name', 'Ticket Site',' First Site Name', 'Job Created']]
# df_new
df_new2019 = df_new.loc[(df_new['Job Created'] <= "2020-01-01 00:00:00.000000") & (df_new['Job Created'] >= "2019-01-01 00:00:00.000000")]

In [ ]:
df_filtered = df_new2019.dropna(subset=['Job ID','Job Created', 'Solution Name'])
catagorical_cols = ['Job ID', 'Solution Name']
#Job Id, Job Created, Ticket Site, Solution Name

In [8]:
from sklearn.preprocessing import StandardScaler, OrdinalEncoder, OneHotEncoder
X_categorical = OneHotEncoder().fit_transform(df_filtered[catagorical_cols].values).toarray()
#make new set in x (issue area/ all inputs) then transform into 2d array

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix, accuracy_score

df_filtered = df_new2019.dropna(subset=['Job ID', 'Job Created', 'Solution Name'])
#create new dataframe the removes rows with missing values for issuearea and direction

X = df_filtered[['Job ID', 'Solution Name']].values
#defines input and reshaped into array with one column and as many rows as there are data points
y = df_filtered['Job Created']
#defines output

X_train, X_test, y_train, y_test = train_test_split(X_categorical, y, test_size=0.3, random_state=42)
# splits input and output variables into 2 sets each, testing set is 30% of the total data, random state ensures reproductibility
#train is part of the data added that is used to compare to the test
#hasnt see part of the data so it isn't 100% correct (data is split off only for training)

mlp = MLPClassifier(random_state=42)
# Create an MLPClassifier

mlp.fit(X_train, y_train)
# Train the classifier on the input and output variables of the training set

y_pred = mlp.predict(X_test)
# Get predictions on the output variable using the trained classifier and the input variable

cm = confusion_matrix(y_test, y_pred)
accuracy = accuracy_score(y_test, y_pred)
# Compute the confusion matrix and accuracy of the predictions compared to true values of output variable.
#confusion matrix gives the number of true positive, true negative, falso pos and flase negative
#accuracy is the proportion of correct predictions out of all predictions

# Print the confusion matrix and accuracy, diagonal should be bigger than top right and bottom left
print(cm)
print(accuracy)


c:\Users\Alaina\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
0.0


In [23]:
df_filtered = df_new2019.dropna(subset=['Job ID', 'Job Created', 'Solution ID'])
#create new dataframe the removes rows with missing values for issuearea and direction
catagorical_cols = ['Job ID', 'Solution ID']

X = df_filtered[['Job ID', 'Solution ID']].values
#defines input and reshaped into array with one column and as many rows as there are data points
y = df_filtered['Job Created']



KeyError: ['Solution ID']

In [20]:

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.decomposition import PCA
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
import pandas as pd


# Load your dataset into a pandas DataFrame (replace 'your_dataset.csv' with your actual dataset file)
df_filtered = df_new2019.dropna(subset=['Job ID', 'Job Created', 'Solution ID'])


# Preprocess your data and create X and y (features and labels)
# For example:
# X = df[['Job ID', 'Solution Name']].values
# y = df['Job Created']
pca = PCA(n_components=50)  # You can adjust the number of components based on your needs
X_pca = pca.fit_transform(X)


# Encode categorical variables

encoder = OneHotEncoder()
X_encoded = encoder.fit_transform(X_pca).toarray()


# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.3, random_state=42)

# Convert NumPy arrays to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).unsqueeze(1)

X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).unsqueeze(1)

# Create DataLoader for training and testing data
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)

test_dataset = TensorDataset(X_test_tensor, y_test_tensor)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

# Define custom neural network model
class NeuralNetwork(nn.Module):
    def __init__(self):
        super(NeuralNetwork, self).__init__()
        self.fc1 = nn.Linear(X_encoded.shape[1], 128)  # Input size is the number of features after encoding
        self.fc2 = nn.Linear(128, 1)  # Output size is 1 for regression task

    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# Initialize the model, loss function, and optimizer
model = NeuralNetwork()
criterion = nn.MSELoss()  # Mean Squared Error loss for regression task
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Train the model
num_epochs = 10
for epoch in range(num_epochs):
    for batch_X, batch_y in train_loader:
        optimizer.zero_grad()
        outputs = model(batch_X)
        loss = criterion(outputs, batch_y)
        loss.backward()
        optimizer.step()

# Evaluate the model
model.eval()
with torch.no_grad():
    test_outputs = model(X_test_tensor)
    mse = criterion(test_outputs, y_test_tensor)
    print("Mean Squared Error on Test Data:", mse.item())




KeyError: ['Solution ID']

In [25]:
jobs2018= df_new2018['Job ID'].unique()
jobsper2018 = len(jobs2018)

In [26]:
jobs2019= df_new2019['Job ID'].unique()
jobsper2019 = len(jobs2019)

In [27]:
jobs2020= df_new2020['Job ID'].unique()
jobsper2020 = len(jobs2020)

In [32]:
jobs2021= df_new2021['Job ID'].unique()
jobsper2021 = len(jobs2021)

In [33]:
jobs2022= df_new2022['Job ID'].unique()
jobsper2022 = len(jobs2022)

In [ ]:
numberofjobsperyear = [jobsper2018, jobsper2019, jobsper2020, jobsper2021, jobsper2022]
yearly_index = ['2018', '2019', '2020', '2021', '2022']

yearly_df = pd.DataFrame({'Number of Jobs' : numberofjobsperyear}, index=yearly_index)

ax = yearly_df.plot.bar(rot=0, title = 'Amount of servers requested per year')

In [38]:
df3 = df['Ticket Site Name'].unique()
df3

array(['CTC-KC-III', 'STCK-25-DC01', 'CTC-LS-IV', 'CTC-KC-I', 'CTC-LS-VI',
       'SLOUGHEQUINIXLD5-DC1', 'CTC-LS-III', 'CTC-KC-II', 'CTC-KC-VIII',
       'MARK-371-FL01', 'CTC-LS-V', 'CTC-KC-VII', nan, 'WGC-20-FL01',
       'CTC-LS-II', 'CTC-KCBUILD1', 'BRISISEEKEAGLE-DC1', 'CLIENT-SITE',
       'UPPLANDS-DS1-DC02', 'BRMP-30-FL01', 'Unanderra-IT3',
       'PAN-110-DC01', 'CTC-LS-IV ', 'CTC-LS-I', 'KALR-39-FL04',
       'MLVN-35-DC01', 'BRISISEEKWLNGABA-DC1', 'BRLN-50-DC01'],
      dtype=object)

In [41]:
df_ticketsite1 = df[(df['Ticket Site Name']=='CTC-KC-III')]
df_ticketsite2 = df[(df['Ticket Site Name']=='STCK-25-DC01')]
df_ticketsite3 = df[(df['Ticket Site Name']=='CTC-LS-IV')]
df_ticketsite4 = df[(df['Ticket Site Name']=='CTC-KC-I')]
df_ticketsite5 = df[(df['Ticket Site Name']=='CTC-LS-VI')]
df_ticketsite6 = df[(df['Ticket Site Name']=='SLOUGHEQUINIXLD5-DC1')]
df_ticketsite7 = df[(df['Ticket Site Name']=='CTC-LS-III')]
df_ticketsite8 = df[(df['Ticket Site Name']=='CTC-KC-II')]
df_ticketsite9 = df[(df['Ticket Site Name']=='CTC-KC-VIII')]
df_ticketsite10 = df[(df['Ticket Site Name']=='MARK-371-FL01')]
ts1 = len(df_ticketsite1)
ts2 = len(df_ticketsite2)
ts3 = len(df_ticketsite3)
ts4 = len(df_ticketsite4)
ts5 = len(df_ticketsite5)
ts6 = len(df_ticketsite6)
ts7 = len(df_ticketsite7)
ts8 = len(df_ticketsite8)
ts9 = len(df_ticketsite9)
ts10 = len(df_ticketsite10)


In [ ]:
numberofjobsatgivendcen = [ts1, ts2, ts3, ts4, ts5, ts6, ts7, ts8, ts9, ts10]
yearly_index = ['CTC-KC-III', 'STCK-25-DC01', 'CTC-LS-IV', 'CTC-KC-I', 'CTC-LS-VI',
       'SLOUGHEQUINIXLD5-DC1', 'CTC-LS-III', 'CTC-KC-II', 'CTC-KC-VIII',
       'MARK-371-FL01']

yearly_df = pd.DataFrame({'Number requested' : numberofjobsatgivendcen}, index = yearly_index)

ax = yearly_df.plot.bar(rot=0, title = 'Amount of servers requested per center total')

In [ ]:

successes_2022_df = df_new2022.loc[df_new2022['Site Name'] == 'CTC-KC-III']
successes_2022_df_values = successes_2022_df.value_counts(['First Site Name'])

# Plotting the data to show the values
successes_2022_df.value_counts(['First Site Name']).sort_values().plot(kind='barh', title='Amount of servers from a specific center')


In [ ]:
len(df)

In [264]:
df['Solution Name'].unique()

array(['Other - VM | Other - VM', 'AX License Server | AXLIC - VM',
       'AX Web Server | AXWS - VM', 'PVS Citrix | PVS Citrix - VM',
       'PVS MGMT | PVS MGMT - VM', 'PVS Master | PVS Master - VM',
       'Citrix Delivery Controller | XDC - VM',
       'Citrix Session Recording | CSR - VM',
       'PVS Gold Master CTX | PVS GM - VM',
       'Olympus Guardian | OLYGD - VM',
       'Domain Controller | Client DC - VM',
       'Cerner Retail Pharmacy | CRPINT - VM', 'Kofax PDF | KFXPDF - VM',
       'Citrix Storefront - External | SF (DMZ) - VM',
       'Citrix Storefront - Internal | SF - VM', 'CSM APP > Non-Prod >VM',
       'Resonance | Resonance', 'Domain Controller | Child DC - VM', nan,
       'Websphere 8.5 LINUX - EAODR | EAODR - VM',
       'Websphere 8.5 LINUX - EAWAS | EAWAS - VM',
       'BE DB Tier->NonProd->DB Tier->Small - VM',
       'PowerInsight Business Object | BO - VM',
       'CareAware iBus | iBus - VM',
       'CareAware Multi Media 7 | DICOM - Cerner DC - VM'

In [25]:
df['Solution Name'].unique()

array([133,  12,  13, 138, 141, 143,  58,  64, 140, 127,  94,  48, 114,
        67,  68,  36, 153,  93, 177, 169, 170,  18, 147,  42,  41, 112,
        17, 104, 128, 100, 164, 156,  95,  99,  98,  89,   4, 130,  82,
        72, 116,  79,  81,  30,  69,  80,  31,  29,  50,  75,  96,   9,
        32, 102, 142, 129, 118, 157, 155,  16,  10, 149,  61,  97,  40,
       105,  74,  90,  73,   6,  60,  62,  45,  44,  43,  77, 148,   1,
       123, 137, 117, 163, 162,  91,  51, 131, 134, 136, 135,   0,   8,
        35,   3,   2, 113, 159, 111,  39,  47, 174, 125, 124,  76, 172,
        87, 173,  14, 108,  83,  66,  37, 132,  49, 146,  78,  70, 145,
        86, 166,  92,  63,  85, 126, 122,  59, 176, 119, 120,  71,  46,
        15, 101, 150,  53,  57, 109, 110,  88,   5, 160,  84,  24,  33,
        56, 106, 107,  54, 152, 158, 103, 121, 151, 115,  34,  19,  65,
       167, 168, 139, 154,  11, 175,  25,  52,  27,  26,  28,  23,   7,
       171, 161, 165,  20,  22,  21,  55, 144,  38])

In [30]:
df['Hardware Site ID'].unique()
#unique server names

array([nan, 'db1c6643-54fd-4d71-ad9c-9f5bd6baf857',
       'b32bd8cb-9709-47ca-93f2-4eab4c26546f',
       'a5bd8b00-e21c-47fa-826c-8aea3ac9f9ea',
       'a3920a41-5eba-4635-a535-82462555337e',
       'eaf716fd-5861-43a9-9b48-d0f00466d723',
       'f1201d70-6cb8-46da-ab7c-0da1204126d7',
       '3d80e882-9f27-4211-a7c5-9ef938661869',
       '0768150d-1804-4da0-9f45-406be1909ba5',
       '71f158a6-76b6-472f-8447-3574c09722f6',
       'dfeb48ef-7579-475a-a3bd-fc34f62cfec8',
       'd4da5d55-4f1a-4b16-9bcd-21c5a06d97c2',
       '4170ceb0-8ddd-46fa-ab0c-a9818820e61f',
       '53801ead-8242-437f-9f8f-e01f14a25217',
       '6f76a25e-887e-404b-b08c-7de9b12c803f',
       '3aa2eb00-320c-4b75-8a41-04e443fdb47b',
       'c29244c6-135f-49d6-97d6-3706a629533b',
       'ddb84ef6-7dda-4e59-9bcb-40c1e75c98e3',
       'f260d454-756c-49f0-9430-eba1d03bca26',
       '67487f1c-43da-4cf5-8831-9ef80abeee55',
       '5056aa76-930d-4756-808c-1b76dafebbf6',
       '77405803-5478-41bf-b783-35c4d4ae7e8a',
       '